version: '3'
services:
  db:
    image: postgres:14.2-alpine
    
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"


  traefik:
      image: "traefik:v2.6.6"
      container_name: "traefik-network"
      command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --log.level=DEBUG
      - --certificatesresolvers.letsencrypt.acme.email=felipeng.eletrica@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      ports:
        - "80:80"
        - "443:443"
      networks:
        - internal
        - web

      volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./acme.json:/acme.json"
      labels:
            # Dashboard
            - "traefik.http.routers.traefik.rule=Host(`dashboard.localhost`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
            - "traefik.http.routers.traefik.middlewares=auth_traefik"
            - "traefik.http.middlewares.auth_traefik.basicauth.users=leonardo:$$2y$$05$$kJfb8phLRJI0grAHzVDdq.3oYkv3kTIsT.2Aosnd8vLp2z1OKPAxm"

  apache:
    image: 'bitnami/apache:2.4.54'
    container_name: apache-network
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    
    labels:
      - traefik.http.routers.apache.rule=Host(`apache.localhost`)
      - traefik.http.routers.apache.tls=true
      - traefik.http.routers.apache.tls.certresolver=lets-encryp
      - traefik.port=8080
    networks:
      - internal
      - web
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    labels:
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
      - traefik.port=3000

    networks:
      - internal
      - web

    environment: 
    - GF_SERVER_HTTP_PORT=3000
    restart: unless-stopped

volumes:
  grafana_data:

networks:
  web:
    external: true
  internal:
    external: false




    




  